#Text prediction Nlp group task

#Group members
##110949 Alvin Irungu
##110695 Adah Kerubo
##108636 David Kiai
##113593 Jafaar Mohammed

In [1]:
import spacy
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import json


In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
from tensorflow.keras.layers import SimpleRNN, GRU, LSTM,Embedding, InputLayer, Input
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize, sent_tokenize
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.optimizers import Adam


In [5]:
data=open("/content/drive/MyDrive/Machine Learning/_chat.txt")
data=data.read()
data


'[18/05/2021, 10:07:12] ICS 4A: \u200eMessages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them.\n[18/05/2021, 10:07:12] \u200eAllen (Class) created this group\n[18/05/2021, 11:16:09] \u200eYou joined using this group\'s invite link\n[18/05/2021, 11:21:49] \u200e\u202a+254\xa0791\xa0278088\u202c joined using this group\'s invite link\n[18/05/2021, 11:22:13] \u200eAdah joined using this group\'s invite link\n[18/05/2021, 11:30:07] \u200e\u202a+254\xa0741\xa0710274\u202c joined using this group\'s invite link\n[18/05/2021, 11:40:03] \u200e\u202a+254\xa0724\xa0438908\u202c joined using this group\'s invite link\n[18/05/2021, 11:47:43] \u200eKahuko joined using this group\'s invite link\n[18/05/2021, 11:54:04] \u200e\u202a+254\xa0703\xa0286773\u202c joined using this group\'s invite link\n[18/05/2021, 11:56:56] \u200e\u202a+254\xa0740\xa0345539\u202c joined using this group\'s invite link\n[18/05/2021, 12:01:24] \u200e\u202a+254

In [6]:
word_tokenize(data)

['[',
 '18/05/2021',
 ',',
 '10:07:12',
 ']',
 'ICS',
 '4A',
 ':',
 '\u200eMessages',
 'and',
 'calls',
 'are',
 'end-to-end',
 'encrypted',
 '.',
 'No',
 'one',
 'outside',
 'of',
 'this',
 'chat',
 ',',
 'not',
 'even',
 'WhatsApp',
 ',',
 'can',
 'read',
 'or',
 'listen',
 'to',
 'them',
 '.',
 '[',
 '18/05/2021',
 ',',
 '10:07:12',
 ']',
 '\u200eAllen',
 '(',
 'Class',
 ')',
 'created',
 'this',
 'group',
 '[',
 '18/05/2021',
 ',',
 '11:16:09',
 ']',
 '\u200eYou',
 'joined',
 'using',
 'this',
 'group',
 "'s",
 'invite',
 'link',
 '[',
 '18/05/2021',
 ',',
 '11:21:49',
 ']',
 '\u200e\u202a+254',
 '791',
 '278088\u202c',
 'joined',
 'using',
 'this',
 'group',
 "'s",
 'invite',
 'link',
 '[',
 '18/05/2021',
 ',',
 '11:22:13',
 ']',
 '\u200eAdah',
 'joined',
 'using',
 'this',
 'group',
 "'s",
 'invite',
 'link',
 '[',
 '18/05/2021',
 ',',
 '11:30:07',
 ']',
 '\u200e\u202a+254',
 '741',
 '710274\u202c',
 'joined',
 'using',
 'this',
 'group',
 "'s",
 'invite',
 'link',
 '[',
 '18/05/

In [7]:
#make a list
chat_list=[]
chats=sent_tokenize(data)
for sent in data:
  chat_list.append([sent])

In [8]:
chats

['[18/05/2021, 10:07:12] ICS 4A: \u200eMessages and calls are end-to-end encrypted.',
 'No one outside of this chat, not even WhatsApp, can read or listen to them.',
 "[18/05/2021, 10:07:12] \u200eAllen (Class) created this group\n[18/05/2021, 11:16:09] \u200eYou joined using this group's invite link\n[18/05/2021, 11:21:49] \u200e\u202a+254\xa0791\xa0278088\u202c joined using this group's invite link\n[18/05/2021, 11:22:13] \u200eAdah joined using this group's invite link\n[18/05/2021, 11:30:07] \u200e\u202a+254\xa0741\xa0710274\u202c joined using this group's invite link\n[18/05/2021, 11:40:03] \u200e\u202a+254\xa0724\xa0438908\u202c joined using this group's invite link\n[18/05/2021, 11:47:43] \u200eKahuko joined using this group's invite link\n[18/05/2021, 11:54:04] \u200e\u202a+254\xa0703\xa0286773\u202c joined using this group's invite link\n[18/05/2021, 11:56:56] \u200e\u202a+254\xa0740\xa0345539\u202c joined using this group's invite link\n[18/05/2021, 12:01:24] \u200e\u202a+254

In [9]:
len(chat_list)

144356

In [10]:
vectorizer=TfidfVectorizer()

In [11]:
x=vectorizer.fit_transform(chats)

In [12]:
vocab=vectorizer.get_feature_names()
len(vocab)#, vocab 

2320

In [13]:
#ctreate embeddings matrix and transposing it
e_array=x.toarray().T
e_array

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.03241848, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [14]:
#creating a dense embedding
#ie, each word will be represented by a vectors of 100 dimensions
pca=PCA(n_components=250)

In [15]:
dense_embed=pca.fit_transform(e_array)
dense_embed

array([[ 0.23986538, -0.01281664,  0.00697159, ..., -0.00497847,
        -0.01070763, -0.03904839],
       [-0.04301575,  0.00327902,  0.0050853 , ..., -0.00170674,
        -0.00778093,  0.03606889],
       [ 0.34807557, -0.0981676 , -0.02784632, ...,  0.00873182,
         0.03155892,  0.01079141],
       ...,
       [ 0.13202609, -0.06425885, -0.06586766, ...,  0.00252601,
         0.01088487,  0.00230878],
       [-0.03753192, -0.00273765,  0.00850439, ..., -0.00163277,
         0.00308457,  0.01546242],
       [-0.02278796,  0.01017641,  0.01869029, ..., -0.00630572,
         0.01243808, -0.01357846]])

In [16]:
#embeddings dictionary
embed_dict={}
for i in range(len(vocab)):
  embed_dict[vocab[i]]=dense_embed[i].tolist()
#21st word becomes the target
seq_len=20
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])
x=tokenizer.texts_to_sequences([data])

In [17]:
len(x),len(x[0])


(1, 26767)

In [18]:
#tokenizer.get_config
vocab_dict=json.loads(tokenizer.get_config().get('word_index'))
vocab_dict

{'2021': 1,
 '\u202a': 2,
 '06': 3,
 '08': 4,
 'the': 5,
 'class': 6,
 '07': 7,
 '05': 8,
 '12': 9,
 'allen': 10,
 'to': 11,
 '16': 12,
 '14': 13,
 '254\xa0740\xa0623000\u202c': 14,
 '15': 15,
 'for': 16,
 '11': 17,
 '10': 18,
 'is': 19,
 '13': 20,
 '09': 21,
 '24': 22,
 '20': 23,
 '21': 24,
 '17': 25,
 'a': 26,
 '22': 27,
 'this': 28,
 '19': 29,
 'i': 30,
 '18': 31,
 '26': 32,
 '28': 33,
 'you': 34,
 'link': 35,
 '23': 36,
 'and': 37,
 'be': 38,
 'on': 39,
 'we': 40,
 '25': 41,
 'in': 42,
 '02': 43,
 '\u200e': 44,
 '254\xa0734\xa0033277\u202c': 45,
 'omitted': 46,
 '30': 47,
 'have': 48,
 'will': 49,
 '03': 50,
 'it': 51,
 'us': 52,
 '27': 53,
 '29': 54,
 'thanks': 55,
 '254\xa0706\xa0907703\u202c': 56,
 'that': 57,
 'https': 58,
 '01': 59,
 'please': 60,
 'cat': 61,
 'of': 62,
 'good': 63,
 '254\xa0772\xa0800237\u202c': 64,
 'was': 65,
 'has': 66,
 'are': 67,
 'people': 68,
 '00': 69,
 '04': 70,
 '31': 71,
 '33': 72,
 'using': 73,
 '46': 74,
 '34': 75,
 '1': 76,
 '39': 77,
 '57': 78,

In [19]:
#keys and values
values=list(vocab_dict.values())
keys=list(vocab_dict.keys())

In [20]:
vocab_len=len(keys)
vocab_len

2530

In [21]:
e_array=np.zeros((vocab_len+1,250))
e_array.shape

(2531, 250)

In [22]:
for word,i in tokenizer.word_index.items():
  if word in embed_dict:
    embed_vector=embed_dict[word]
    e_array[i]=embed_vector #where the vector isnt none

In [23]:
len(x[0])

26767

In [24]:
x[0][0:15]

[31, 8, 1, 18, 7, 9, 298, 561, 1212, 37, 1213, 67, 359, 11, 359]

In [25]:
inner_list=[]
X={}
corp_len=len(x[0])-seq_len
k=0

for i in range(0, corp_len, seq_len):
  inner_list.clear()
  for j in range(i, i+seq_len):
    inner_list.append(x[0][j])
  X[k]=inner_list[:]
  k=k+1

In [26]:
#list xvalues
x_train=[]
y_train=[]
for num in list(X.values()):
  x_train.append(num[0:-1])
  y_train.append(num[-1])

In [27]:
len(x_train)

1338

In [28]:
X=np.array(x_train)
y=np.array(y_train).reshape(len(y_train),1)

In [29]:
X.shape, y.shape

((1338, 19), (1338, 1))

In [30]:
y_train

[62,
 860,
 24,
 79,
 17,
 28,
 1,
 101,
 9,
 28,
 1,
 93,
 7,
 79,
 41,
 28,
 1,
 101,
 31,
 108,
 35,
 103,
 79,
 26,
 6,
 139,
 2,
 154,
 31,
 1238,
 45,
 108,
 691,
 1246,
 2,
 29,
 109,
 866,
 275,
 82,
 1,
 695,
 2,
 108,
 93,
 6,
 21,
 19,
 397,
 134,
 37,
 8,
 114,
 21,
 8,
 451,
 66,
 23,
 6,
 23,
 14,
 144,
 24,
 875,
 16,
 13,
 1274,
 24,
 32,
 24,
 455,
 51,
 1278,
 5,
 22,
 4,
 65,
 139,
 44,
 574,
 32,
 2,
 2,
 8,
 22,
 22,
 13,
 94,
 80,
 5,
 155,
 134,
 18,
 22,
 28,
 19,
 562,
 2,
 17,
 1303,
 57,
 1306,
 133,
 372,
 92,
 80,
 132,
 2,
 8,
 2,
 891,
 8,
 721,
 25,
 173,
 106,
 48,
 1321,
 900,
 715,
 323,
 1,
 35,
 729,
 2,
 90,
 8,
 131,
 8,
 28,
 466,
 8,
 24,
 126,
 12,
 98,
 4,
 130,
 1,
 134,
 8,
 308,
 306,
 19,
 64,
 1,
 35,
 2,
 2,
 36,
 33,
 9,
 900,
 87,
 101,
 1,
 111,
 71,
 1354,
 235,
 376,
 109,
 277,
 45,
 84,
 84,
 1,
 67,
 24,
 146,
 305,
 1366,
 39,
 64,
 75,
 82,
 183,
 17,
 596,
 1373,
 52,
 14,
 477,
 221,
 4,
 6,
 261,
 45,
 2,
 132,
 2,
 1,
 246,

In [31]:
x_train,x_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=101)

In [32]:
#x_train= input_seq
#x_hat=test_seq
#create tensors to put the matriz in
input_seq,test_seq,y_true,y_hat=tf.constant(x_train),tf.constant(x_test),tf.constant(y_train),tf.constant(y_test)
                                                         

In [33]:
len(X), len(input_seq),len(test_seq)

(1338, 1070, 268)

In [34]:
input_seq

<tf.Tensor: shape=(1070, 19), dtype=int64, numpy=
array([[ 270,  823,  210, ...,    7,    1,   24],
       [  50,    2,  115, ...,   64,   83,  218],
       [ 130,    9,    2, ...,    5, 1777,   60],
       ...,
       [  72,    2,   56, ...,   22,    8,    1],
       [  37,  284,  281, ...,  923,   22,    3],
       [   1,   20,   72, ...,   46,   44,   13]])>

In [35]:
#prediction/ target
y_true

<tf.Tensor: shape=(1070, 1), dtype=int64, numpy=
array([[  3],
       [ 57],
       [269],
       ...,
       [  4],
       [  1],
       [  7]])>

In [36]:
#loss function is sparse_categorical_crossentropy, because the dataset is rather large
#the metrics beung tracked is accuracy as we want to see how accurately the model can predict the next word(s)

In [37]:
#create the model
model_1=tf.keras.Sequential([
                             tf.keras.layers.Embedding(input_dim=vocab_len+1, output_dim=250, trainable=True, weights=[e_array]),
                             tf.keras.layers.LSTM(128, return_sequences=True),
                             tf.keras.layers.LSTM(128, return_sequences=True),
                             tf.keras.layers.LSTM(128, activation="relu"),
                             tf.keras.layers.Dense(100, activation="relu"),
                             tf.keras.layers.Dense(100, activation="relu"),
                             tf.keras.layers.Dense(vocab_len, activation="softmax")
                             ])
model_1.summary()
#compile model
model_1.compile(loss=tf.keras.losses.sparse_categorical_crossentropy,
                optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                metrics=['accuracy']
                 )
#fit/train
model_1.fit(input_seq, y_true, epochs=130, verbose=1)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 250)         632750    
_________________________________________________________________
lstm (LSTM)                  (None, None, 128)         194048    
_________________________________________________________________
lstm_1 (LSTM)                (None, None, 128)         131584    
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dense (Dense)                (None, 100)               12900     
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 2530)              2

In [44]:
#Improving the model
#1..Better embeddings ie incr the output dimensions
##ie at pca=PCA(n_components=100) 
#and 
##at e_array=np.zeros((vocab_len+1,200))

#2..train for longer
#3..more epochs
#4..more layers

In [45]:
#evaluate model against test set
model_1.evaluate(test_seq, y_hat)

9/9 [==============================] - 0s 11ms/step - loss: 18.1786 - accuracy: 0.0336


[18.178607940673828, 0.033582091331481934]

In [57]:
#checking what it will predict
#input_text=["The cat has bounced"]#should predict either cat or class or something in that context
input_text=["Allen is our"]
tok=tokenizer.texts_to_sequences(input_text) 
ins=pad_sequences(tok, maxlen=seq_len-1)
input_tensor=tf.constant(ins)
input_tensor

<tf.Tensor: shape=(1, 19), dtype=int32, numpy=
array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  10,  19, 278]], dtype=int32)>

In [58]:
#make predictions
prediction=model_1.predict(input_tensor)
keys[values.index(np.argmax(prediction))]

'16'

In [56]:
input_text[0]=input_text[0]+' '+keys[values.index(np.argmax(prediction))]
input_text[0]

'Allen is our 16'

In [51]:
for i in range(10):
  tok=tokenizer.texts_to_sequences(input_text)
  ins=pad_sequences(tok, maxlen=seq_len-1)
  input_tensor=tf.constant(ins)
  prediction=model_1.predict(input_tensor)
  input_text[0]=input_text[0]+' '+keys[values.index(np.argmax(prediction))]

  print(input_text)

['when is the cat google si']
['when is the cat google si si']
['when is the cat google si si gradient']
['when is the cat google si si gradient systems']
['when is the cat google si si gradient systems i’ve']
['when is the cat google si si gradient systems i’ve touch']
['when is the cat google si si gradient systems i’ve touch touch']
['when is the cat google si si gradient systems i’ve touch touch just']
['when is the cat google si si gradient systems i’ve touch touch just tools']
['when is the cat google si si gradient systems i’ve touch touch just tools then']
